### ISSUE TITLE
koffeinfrei in Health

### ISSUE THREAD

**Issue by AlBertyBundy** [Beanconqueror/beanconqueror.github.io#1]
Hallo,

wenn ich bei einer Bohnensorte „koffeinfrei“ auswähle, wird trotzdem ein Eintrag (mit) Koffein in Health gemacht.

Viele Grüße

**Comment by graphefruit** [comment]
Hallo!
Danke fürs melden, ich hab den Fehler im App-Projekt aufgemacht: https://github.com/graphefruit/Beanconqueror/issues/258

Daher wird dieser hier geschlossen.
Viele Grüße
Lars

**Comment by AlBertyBundy** [comment]
Danke
